# Generated by Django 5.1.4 on 2025-01-25 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.PositiveIntegerField(unique=True)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('salario', models.FloatField()),
                ('cargo', models.CharField(choices=[('Farmacéutico', 'Farmacéutico'), ('Administrador', 'Administrador')], max_length=15)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.farmacia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.farmacia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('fecha', models.DateField()),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de crédito', 'Tarjeta de crédito'), ('Tarjeta de débito', 'Tarjeta de débito')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.empleado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.farmacia')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.sucursal'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='sucursal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sistema.sucursal'),
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('fecha', models.DateField()),
                ('completada', models.BooleanField(default=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='Sistema.sucursal')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.empleado')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origen', to='Sistema.sucursal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.producto')),
            ],
        ),
    ]
