# Generated by Django 5.1.4 on 2025-01-26 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_pedido_items_pedido_alter_factura_descuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='items_pedido',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Sistema.pedido'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.inventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.producto')),
            ],
            options={
                'unique_together': {('producto', 'inventario')},
            },
        ),
        migrations.AddField(
            model_name='itempedido',
            name='producto_inventario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema.productoinventario'),
        ),
        migrations.DeleteModel(
            name='ItemFactura',
        ),
    ]
