# Generated by Django 5.1.4 on 2025-01-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_remove_itempedido_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_disponible',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
