# Generated by Django 5.1.4 on 2025-01-26 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0005_remove_producto_cantidad_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_sucursal_actual', to='Sistema.sucursal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_origen', to='Sistema.sucursal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('Retiro en origen', 'Retiro en origen'), ('Retiro en sucursal actual', 'Retiro en sucursal actual')], default='Retiro en origen', max_length=30),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema.empleado'),
        ),
    ]
