# Generated by Django 5.1.4 on 2025-01-27 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Farmacia.cliente'),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='sucursal_actual',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='sucursal_origen',
        ),
        migrations.RemoveField(
            model_name='productoinventario',
            name='precio',
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Farmacia.sucursal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
