# Generated by Django 5.1.4 on 2025-01-27 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0002_remove_empleado_user_remove_cliente_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmacia.sucursal'),
        ),
    ]
