# Generated by Django 5.1.4 on 2025-01-27 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0003_alter_pedido_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Farmacia.sucursal'),
        ),
    ]
