# Generated by Django 5.1.4 on 2025-01-27 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0005_alter_pedido_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='Farmacia.sucursal'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origen', to='Farmacia.sucursal'),
        ),
    ]
