# Generated by Django 5.1.4 on 2025-01-27 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0005_transferencia_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='pedido',
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
    ]
