# Generated by Django 5.1.4 on 2025-01-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0006_alter_transferencia_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='inventario',
        ),
    ]
