# Generated by Django 5.1.4 on 2025-01-31 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0007_delete_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='descuento',
        ),
        migrations.AddField(
            model_name='factura',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='factura',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_list', to='Farmacia.producto'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencia_list', to='Farmacia.producto'),
        ),
    ]
