# Generated by Django 5.1.4 on 2025-01-31 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0008_remove_factura_descuento_factura_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cambio',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='dinero_recibido',
        ),
        migrations.AddField(
            model_name='factura',
            name='inventario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Farmacia.inventario'),
        ),
    ]
