# Generated by Django 5.1.4 on 2025-01-31 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0009_remove_factura_cambio_remove_factura_dinero_recibido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='producto',
        ),
    ]
